export const MOMENT_EVALUATION_TEMPLATE = `
A moment is an on-chain NFT that is published on Remx by a Creator.
Moments represent some artistic expression and may include works in progress or finished art.
They may be created by the artist as either physical or digital pieces and may be generated by AI.

# Generation Template (do not use the sample values in your response):
\`\`\`json
  {
    "summary": "Sample summary of some moment.",
    "comment": "Sample comment to leave on the moment.",
    "
    "action": "LIKE"
  }
  \`\`\`

Analyze the following moment using the image description and associated title, description and tags.
Produce the following information in a JSON format using the generation template provided:
- a summary of the content of the moment in one or two sentences,
- a comment to leave on the moment for the author about the moment and why you like it
- an opinion about whether you like it or not with a short explanation
- an action to take on the moment.

If you are not sure about the action to take, you can choose to IGNORE the moment.
If you LIKE the moment, you must provide a comment suitable for posting in a public forum.

Actions that can be taken on a moment are:
- LIKE
- IGNORE

About the creator:
{creatorName}
{creatorBio}

Moment:
IMAGE DESCRIPTION: {imageDescription}
TITLE: {title}
DESCRIPTION: {description}
TAGS: {tags}
`
